### ISSUE TITLE
RHEL 6: Have to run mrepo -u multiple times to get all updates

### ISSUE THREAD

**Issue by NeoZer0** [dagwieers/mrepo#41]
I'm not sure if anyone else has seen this issue.  I am using mrepo to maintain repos for RHEL 5 (32 bit), RHEL 6 (64bit), SLES 10 SP4 (32, 64bit) and SLES 11 SP1 (32, 64bit).  My Red Hat repos are fine but my SLES repos aren't updated with all updates unless I run mepo -u multiple times.  Anyone have any ideas?

**Comment by sbeee** [comment]
Hi,
it seems i've the same problems. Can you share your code with me!?
