### ISSUE TITLE
repodata directory missing from mirrors created by mrepo 

### ISSUE THREAD

**Issue by tfhartmann** [dagwieers/mrepo#72]
I'm trying to mirror a couple of the repos from repos.fedorapeople.org with mrepo, and when mrepo completes its run, the packages appear just fine, but the repodata isn't generated in the repos. I can get it to generate the repodata directories and files by passing the --force argument to mrepo  but that doesn't seem like the correct behavior... (or is it?) 

I may be missing something simple here...

**Comment by jmauro** [comment]
Hey @tfhartmann,

What is the command line you are running?

Regards,
JM
